customhost = "employee.cmy6rehaucwl.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leongwaihang-employee"
customregion = "us-east-1"
